Repository HEIG-Boom/BridgeHack, pull requests merged in 2019-06, with the labels that each got.

#24 Fixed the map and added layer for collisions
  src/main/java/ch/heigvd/mcr/bridgehack/Map.java
  src/main/java/ch/heigvd/mcr/bridgehack/player/Player.java
  src/main/resources/maps/BridgeHack.tsx
  src/main/resources/maps/map1.tmx
  src/main/resources/maps/newMap.tmx
  src/main/resources/maps/untitled.tsx
Labels: Map

#28 Races and roles
  BridgeHack.sly
  src/main/java/ch/heigvd/mcr/bridgehack/BridgeHack.java
  src/main/java/ch/heigvd/mcr/bridgehack/player/Player.java
  src/main/java/ch/heigvd/mcr/bridgehack/player/races/Dwarf.java
  src/main/java/ch/heigvd/mcr/bridgehack/player/races/Elf.java
  src/main/java/ch/heigvd/mcr/bridgehack/player/races/Human.java
  src/main/java/ch/heigvd/mcr/bridgehack/player/roles/Hunter.java
  src/main/java/ch/heigvd/mcr/bridgehack/player/roles/Knight.java
  src/main/java/ch/heigvd/mcr/bridgehack/player/roles/Role.java
  src/main/java/ch/heigvd/mcr/bridgehack/player/roles/Wizard.java
  src/main/resources/img/wizzard_f_hit_anim_f0.png
  src/main/resources/img/wizzard_f_run_anim_f0.png
  src/main/resources/img/wizzard_f_run_anim_f1.png
  src/main/resources/img/wizzard_f_run_anim_f2.png
  src/main/resources/img/wizzard_f_run_anim_f3.png
  src/main/resources/img/wizzard_m_hit_anim_f0.png
  src/main/resources/img/wizzard_m_run_anim_f0.png
  src/main/resources/img/wizzard_m_run_anim_f1.png
  src/main/resources/img/wizzard_m_run_anim_f2.png
  src/main/resources/img/wizzard_m_run_anim_f3.png
Labels: Players

#29 Add new map (map3)
  src/main/resources/maps/map3.tmx
Labels: Map

#30 Switches from map to map, generates random positions, added state for…
  src/main/java/ch/heigvd/mcr/bridgehack/BridgeHack.java
  src/main/java/ch/heigvd/mcr/bridgehack/Map.java
  src/main/java/ch/heigvd/mcr/bridgehack/player/Player.java
  src/main/java/ch/heigvd/mcr/bridgehack/player/State.java
  src/main/java/ch/heigvd/mcr/bridgehack/player/races/Dwarf.java
  src/main/java/ch/heigvd/mcr/bridgehack/player/races/Elf.java
  src/main/java/ch/heigvd/mcr/bridgehack/player/races/Human.java
  src/main/resources/maps/map2.tmx
Labels: Map, Players

#33 Add race and enemy classes
  src/main/java/ch/heigvd/mcr/bridgehack/player/Enemy.java
  src/main/java/ch/heigvd/mcr/bridgehack/player/Player.java
  src/main/java/ch/heigvd/mcr/bridgehack/player/races/Race.java
Labels: Players

#36 Fix compile errors, add IntVector class
  BridgeHack.sly
  src/main/java/ch/heigvd/mcr/bridgehack/game/Map.java
  src/main/java/ch/heigvd/mcr/bridgehack/game/state/GameState.java
  src/main/java/ch/heigvd/mcr/bridgehack/player/Player.java
  src/main/java/ch/heigvd/mcr/bridgehack/player/races/Dwarf.java
  src/main/java/ch/heigvd/mcr/bridgehack/player/races/Elf.java
  src/main/java/ch/heigvd/mcr/bridgehack/player/races/Human.java
  src/main/java/ch/heigvd/mcr/bridgehack/player/races/Race.java
  src/main/java/ch/heigvd/mcr/bridgehack/utils/IntVector.java
  src/test/java/ch/heigvd/mcr/bridgehack/AppTest.java
Labels: Players

#40 Move rendering to the Role class, fixed role appearance
  src/main/java/ch/heigvd/mcr/bridgehack/Item/potion/Potion.java
  src/main/java/ch/heigvd/mcr/bridgehack/Item/potion/TransformPotion.java
  src/main/java/ch/heigvd/mcr/bridgehack/game/state/GameState.java
  src/main/java/ch/heigvd/mcr/bridgehack/player/Player.java
  src/main/java/ch/heigvd/mcr/bridgehack/player/races/Race.java
  src/main/java/ch/heigvd/mcr/bridgehack/player/roles/Hunter.java
  src/main/java/ch/heigvd/mcr/bridgehack/player/roles/Knight.java
  src/main/java/ch/heigvd/mcr/bridgehack/player/roles/Role.java
  src/main/java/ch/heigvd/mcr/bridgehack/player/roles/Wizard.java
Labels: Items, Players

#46 Enemies implementation
  src/main/java/ch/heigvd/mcr/bridgehack/Item/potion/HealthPotion.java
  src/main/java/ch/heigvd/mcr/bridgehack/Item/potion/ManaPotion.java
  src/main/java/ch/heigvd/mcr/bridgehack/Item/potion/Potion.java
  src/main/java/ch/heigvd/mcr/bridgehack/Item/potion/TransformPotion.java
  src/main/java/ch/heigvd/mcr/bridgehack/Item/weapon/BareHanded.java
  src/main/java/ch/heigvd/mcr/bridgehack/Item/weapon/Bow.java
  src/main/java/ch/heigvd/mcr/bridgehack/Item/weapon/Staff.java
  src/main/java/ch/heigvd/mcr/bridgehack/Item/weapon/Sword.java
  src/main/java/ch/heigvd/mcr/bridgehack/Item/weapon/Weapon.java
  src/main/java/ch/heigvd/mcr/bridgehack/character/Character.java
  src/main/java/ch/heigvd/mcr/bridgehack/character/Enemy.java
  src/main/java/ch/heigvd/mcr/bridgehack/character/Player.java
  src/main/java/ch/heigvd/mcr/bridgehack/character/State.java
  src/main/java/ch/heigvd/mcr/bridgehack/character/races/Dwarf.java
  src/main/java/ch/heigvd/mcr/bridgehack/character/races/Elf.java
  src/main/java/ch/heigvd/mcr/bridgehack/character/races/Human.java
  src/main/java/ch/heigvd/mcr/bridgehack/character/races/Race.java
  src/main/java/ch/heigvd/mcr/bridgehack/character/roles/Hunter.java
  src/main/java/ch/heigvd/mcr/bridgehack/character/roles/Knight.java
  src/main/java/ch/heigvd/mcr/bridgehack/character/roles/Role.java
  src/main/java/ch/heigvd/mcr/bridgehack/character/roles/Wizard.java
  src/main/java/ch/heigvd/mcr/bridgehack/game/Map.java
  src/main/java/ch/heigvd/mcr/bridgehack/game/state/GameState.java
  src/main/java/ch/heigvd/mcr/bridgehack/player/Enemy.java
  src/main/java/ch/heigvd/mcr/bridgehack/utils/IntVector.java
Labels: Map, Players

#43 Added Undead race and Enemy role
  src/main/java/ch/heigvd/mcr/bridgehack/character/Character.java
  src/main/java/ch/heigvd/mcr/bridgehack/character/races/Undead.java
  src/main/java/ch/heigvd/mcr/bridgehack/character/roles/BadGuy.java
  src/main/java/ch/heigvd/mcr/bridgehack/game/Map.java
  src/main/java/ch/heigvd/mcr/bridgehack/game/state/GameState.java
  src/main/resources/img/knight_f_hit_anim_f0.png
  src/main/resources/img/knight_f_idle_anim_f0.png
  src/main/resources/img/knight_f_idle_anim_f1.png
  src/main/resources/img/knight_f_idle_anim_f2.png
  src/main/resources/img/knight_f_idle_anim_f3.png
  src/main/resources/img/knight_f_run_anim_f0.png
  src/main/resources/img/knight_f_run_anim_f1.png
  src/main/resources/img/knight_f_run_anim_f2.png
  src/main/resources/img/knight_f_run_anim_f3.png
Labels: Players

#53 Fix enemies turn
  src/main/java/ch/heigvd/mcr/bridgehack/character/Character.java
  src/main/java/ch/heigvd/mcr/bridgehack/character/Enemy.java
  src/main/java/ch/heigvd/mcr/bridgehack/character/Player.java
  src/main/java/ch/heigvd/mcr/bridgehack/game/Map.java
  src/main/java/ch/heigvd/mcr/bridgehack/game/state/GameState.java
Labels: Gameplay, Players

#54 Cleanup of "my" packages, fixed typos
  BridgeHack.sly
  src/main/java/ch/heigvd/mcr/bridgehack/App.java
  src/main/java/ch/heigvd/mcr/bridgehack/character/Character.java
  src/main/java/ch/heigvd/mcr/bridgehack/character/Enemy.java
  src/main/java/ch/heigvd/mcr/bridgehack/character/Player.java
  src/main/java/ch/heigvd/mcr/bridgehack/character/StatModifier.java
  src/main/java/ch/heigvd/mcr/bridgehack/character/State.java
  src/main/java/ch/heigvd/mcr/bridgehack/character/races/Elf.java
  src/main/java/ch/heigvd/mcr/bridgehack/character/races/Human.java
  src/main/java/ch/heigvd/mcr/bridgehack/character/races/Race.java
  src/main/java/ch/heigvd/mcr/bridgehack/character/races/RaceType.java
  src/main/java/ch/heigvd/mcr/bridgehack/character/roles/BadGuy.java
  src/main/java/ch/heigvd/mcr/bridgehack/character/roles/Hunter.java
  src/main/java/ch/heigvd/mcr/bridgehack/character/roles/Knight.java
  src/main/java/ch/heigvd/mcr/bridgehack/character/roles/Role.java
  src/main/java/ch/heigvd/mcr/bridgehack/character/roles/RoleType.java
  src/main/java/ch/heigvd/mcr/bridgehack/character/roles/Wizard.java
  src/main/java/ch/heigvd/mcr/bridgehack/game/state/LoseState.java
  src/main/java/ch/heigvd/mcr/bridgehack/game/state/WinState.java
  src/main/java/ch/heigvd/mcr/bridgehack/utils/CheckBox.java
  src/main/java/ch/heigvd/mcr/bridgehack/utils/IntVector.java
Labels: Players
